"""Generate the synthetic seed corpus, for testing the harness only.

These documents were constructed to contain the failures they demonstrate, so
numbers computed on them prove the *harness* works and prove nothing about any
model. They live under `corpus-synthetic/` and never under `corpus/`, because a
synthetic benchmark result presented as a real one is precisely the kind of
claim this project exists to catch.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

AGENTS = Path(__file__).resolve().parents[1]
for extra in (AGENTS / "src", AGENTS / "examples", AGENTS / "evals"):
    sys.path.insert(0, str(extra))

import document_intake.app as app  # noqa: E402
from dataset import DATASET  # noqa: E402
from personas import PERSONAS, build_policy  # noqa: E402

from pyligent_agents.testing import build_test_stack  # noqa: E402

OUT = Path(__file__).resolve().parent / "corpus-synthetic"


def main() -> int:
    OUT.mkdir(exist_ok=True)
    made = 0
    for case in DATASET:
        d = OUT / case.case_id.replace("/", "__")
        (d / "extractions").mkdir(parents=True, exist_ok=True)
        (d / "source.txt").write_text(case.source_text)
        (d / "meta.json").write_text(json.dumps({
            "source_url": "",
            "licence": "synthetic, generated by pyligent-agents evals",
            "warning": "CONSTRUCTED to contain specific failures. Not a benchmark.",
            "kind": case.kind,
        }, indent=2))
        for name in PERSONAS:
            stack = build_test_stack(build_policy(case, name))
            r = stack.runner(app.build_graph(stack.harness, case.kind,
                                             source=case.source_text)).start("x", {})
            fields = (r.state.get("artifact") or {}).get("fields") or {}
            (d / "extractions" / f"{name}.json").write_text(json.dumps(
                {"fields": {k: {"value": v.get("value"),
                                "quote": v.get("evidence_quote", "")}
                            for k, v in fields.items() if isinstance(v, dict)}},
                indent=2))
        made += 1
    print(f"{made} synthetic document(s) with {len(PERSONAS)} extraction(s) each")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
